// src/constants/mockData.js
// ─────────────────────────────────────────────────────────────
// DEFAULT LOGIN CREDENTIALS
// ─────────────────────────────────────────────────────────────
export const DEMO_USERS = [
  {
    id: 1,
    empId: 'EMP001',
    password: 'emp123',
    name: 'Ankush Gulwani',
    email: 'ankush@cdgi.edu.in',
    role: 'EMPLOYEE',
    designation: 'Assistant Professor',
    department: 'Computer Science & Engineering',
    departmentId: 1,
    avatar: 'AG',
    joinDate: '2021-07-01',
  },
  {
    id: 2,
    empId: 'EMP002',
    password: 'emp123',
    name: 'Priya Sharma',
    email: 'priya@cdgi.edu.in',
    role: 'EMPLOYEE',
    designation: 'Lab Assistant',
    department: 'Electronics Engineering',
    departmentId: 2,
    avatar: 'PS',
    joinDate: '2020-08-15',
  },
  {
    id: 3,
    empId: 'HOD001',
    password: 'hod123',
    name: 'Dr. Radheshyam Acholiya',
    email: 'hod.cse@cdgi.edu.in',
    role: 'HOD',
    designation: 'Head of Department',
    department: 'Computer Science & Engineering',
    departmentId: 1,
    avatar: 'RA',
    joinDate: '2015-06-01',
  },
  {
    id: 4,
    empId: 'Lib123',
    password: 'lib123',
    name: 'Mr. Suresh Librarian',
    email: 'library@cdgi.edu.in',
    role: 'HOD',
    designation: 'Chief Librarian',
    department: 'Library',
    departmentId: 5,
    avatar: 'SL',
    joinDate: '2016-01-10',
  },
  {
    id: 5,
    empId: 'ADMIN001',
    password: 'admin123',
    name: 'Dr. Manoj Agrawal',
    email: 'admin@cdgi.edu.in',
    role: 'ADMIN',
    designation: 'HR Manager / Administrator',
    department: 'Human Resources',
    departmentId: 0,
    avatar: 'MA',
    joinDate: '2010-04-01',
  },
]

export const DEPARTMENTS = [
  { id: 1, name: 'Computer Science & Engineering' },
  { id: 2, name: 'Electronics Engineering' },
  { id: 3, name: 'Mechanical Engineering' },
  { id: 4, name: 'Civil Engineering' },
  { id: 5, name: 'Library' },
  { id: 6, name: 'Accounts / Finance' },
  { id: 7, name: 'IT Department' },
  { id: 8, name: 'Canteen' },
  { id: 9, name: 'Office / Admin' },
]

// Clearance chain departments (always required for no-dues)
export const CLEARANCE_DEPARTMENTS = [
  { id: 5,  name: 'Library',           icon: '📚' },
  { id: 6,  name: 'Accounts',          icon: '💰' },
  { id: 7,  name: 'IT Department',     icon: '💻' },
  { id: 8,  name: 'Canteen',           icon: '🍽️' },
  { id: 9,  name: 'Office / Admin',    icon: '🏢' },
  { id: 1,  name: 'HOD (Dept)',        icon: '👨‍🏫' },
]

export const MOCK_REQUESTS = [
  {
    id: 'REQ-2025-001',
    empId: 1,
    empName: 'Ankush Gulwani',
    empCode: 'EMP001',
    designation: 'Assistant Professor',
    department: 'Computer Science & Engineering',
    submittedAt: '2025-01-12',
    reason: 'Resignation',
    overallStatus: 'IN_PROGRESS',
    documents: ['experience_letter.pdf', 'resignation_letter.pdf'],
    departmentStatuses: [
      { deptId: 5, deptName: 'Library',      status: 'APPROVED', remarks: 'No pending books.', approvedAt: '2025-01-13', approvedBy: 'Mr. Suresh' },
      { deptId: 6, deptName: 'Accounts',     status: 'APPROVED', remarks: 'No financial dues.', approvedAt: '2025-01-13', approvedBy: 'Mrs. Kavita' },
      { deptId: 7, deptName: 'IT Department',status: 'PENDING',  remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 8, deptName: 'Canteen',      status: 'PENDING',  remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 9, deptName: 'Office / Admin',status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 1, deptName: 'HOD (Dept)',   status: 'PENDING',  remarks: '', approvedAt: null, approvedBy: null },
    ],
  },
  {
    id: 'REQ-2025-002',
    empId: 2,
    empName: 'Priya Sharma',
    empCode: 'EMP002',
    designation: 'Lab Assistant',
    department: 'Electronics Engineering',
    submittedAt: '2025-01-08',
    reason: 'End of Contract',
    overallStatus: 'APPROVED',
    documents: ['contract_end_letter.pdf'],
    departmentStatuses: [
      { deptId: 5, deptName: 'Library',       status: 'APPROVED', remarks: 'Cleared.', approvedAt: '2025-01-09', approvedBy: 'Mr. Suresh' },
      { deptId: 6, deptName: 'Accounts',      status: 'APPROVED', remarks: 'All dues cleared.', approvedAt: '2025-01-09', approvedBy: 'Mrs. Kavita' },
      { deptId: 7, deptName: 'IT Department', status: 'APPROVED', remarks: 'Laptop returned.', approvedAt: '2025-01-10', approvedBy: 'Mr. Ravi' },
      { deptId: 8, deptName: 'Canteen',       status: 'APPROVED', remarks: 'No dues.', approvedAt: '2025-01-10', approvedBy: 'Mr. Ramesh' },
      { deptId: 9, deptName: 'Office / Admin',status: 'APPROVED', remarks: 'Cleared.', approvedAt: '2025-01-11', approvedBy: 'Ms. Neeta' },
      { deptId: 1, deptName: 'HOD (Dept)',    status: 'APPROVED', remarks: 'All clear.', approvedAt: '2025-01-12', approvedBy: 'Dr. R.K. Jain' },
    ],
  },
  {
    id: 'REQ-2025-003',
    empId: 1,
    empName: 'Rohit Verma',
    empCode: 'EMP003',
    designation: 'Associate Professor',
    department: 'Computer Science & Engineering',
    submittedAt: '2025-01-14',
    reason: 'Resignation',
    overallStatus: 'PENDING',
    documents: [],
    departmentStatuses: [
      { deptId: 5, deptName: 'Library',       status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 6, deptName: 'Accounts',      status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 7, deptName: 'IT Department', status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 8, deptName: 'Canteen',       status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 9, deptName: 'Office / Admin',status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 1, deptName: 'HOD (Dept)',    status: 'PENDING', remarks: '', approvedAt: null, approvedBy: null },
    ],
  },
  {
    id: 'REQ-2025-004',
    empId: 6,
    empName: 'Sunita Patel',
    empCode: 'EMP004',
    designation: 'Accountant',
    department: 'Accounts / Finance',
    submittedAt: '2025-01-10',
    reason: 'Retirement',
    overallStatus: 'REJECTED',
    documents: ['retirement_notice.pdf'],
    departmentStatuses: [
      { deptId: 5, deptName: 'Library',       status: 'APPROVED', remarks: 'Cleared.', approvedAt: '2025-01-11', approvedBy: 'Mr. Suresh' },
      { deptId: 6, deptName: 'Accounts',      status: 'REJECTED', remarks: 'Outstanding dues of Rs. 2,500 pending. Please clear before resubmitting.', approvedAt: '2025-01-12', approvedBy: 'Mrs. Kavita' },
      { deptId: 7, deptName: 'IT Department', status: 'PENDING',  remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 8, deptName: 'Canteen',       status: 'APPROVED', remarks: 'No dues.', approvedAt: '2025-01-11', approvedBy: 'Mr. Ramesh' },
      { deptId: 9, deptName: 'Office / Admin',status: 'PENDING',  remarks: '', approvedAt: null, approvedBy: null },
      { deptId: 1, deptName: 'HOD (Dept)',    status: 'PENDING',  remarks: '', approvedAt: null, approvedBy: null },
    ],
  },
]

export const STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

export const ROLES = {
  EMPLOYEE: 'EMPLOYEE',
  HOD: 'HOD',
  ADMIN: 'ADMIN',
}
